### PR TITLE
feat: add node info bar

### PR DESCRIPTION
**Pull request by alanshaw**
Shows information about the node that is in focus.

Screenshot 2019-05-15 at 11 43 04
Screenshot 2019-05-15 at 11 40 44
Screenshot 2019-05-15 at 11 40 33
Screenshot 2019-05-15 at 11 40 30
screenshot

### CODE REVIEW

**Comment by olizilla** [comment]
O M GEEeeeEeeer

**Comment by olizilla** [comment]
1. how did you get a directory in there? Derping dirs on their aint working for me.
2. why no links count in the UnixFS Directory stats?

**Comment by alanshaw** [comment]
>     1. how did you get a directory in there? Derping dirs on their aint working for me.

Right now you can drop another file on the graph after you drop the first. Needs another PR for supporting selecting/dropping multiple/directory.

>     2. why no links count in the UnixFS Directory stats?

Good point. It needs to get fixed. I'm using `blockSizes.length` but for unixfs directories these don't exist for some reason.

**Comment by alanshaw** [comment]
@olizilla is a good PR tho?

**Comment by olizilla** [comment]
very very good

**Pull request merged**
